add mypy and fix many type related errors and bugs

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -211,6 +211,45 @@ jobs:
           . venv/bin/activate
           pre-commit run --hook-stage manual codespell --all-files --show-diff-on-failure
 
+  run-mypy:
+    name: Run mypy
+    runs-on: ubuntu-20.04
+    needs: [prepare-python-venv, prepare-pre-commit]
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.1.0
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v4.3.0
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v3.0.11
+        with:
+          path: venv
+          key: ${{ needs.prepare-python-venv.outputs.python-venv-cache-key }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Restore pre-commit environment from cache
+        id: cache-pre-commit
+        uses: actions/cache@v3.0.11
+        with:
+          path: ${{ env.PRE_COMMIT_CACHE }}
+          key: ${{ needs.prepare-pre-commit.outputs.pre-commit-cache-key }}
+      - name: Fail job if pre-commit cache restore failed
+        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore pre-commit environment from cache"
+          exit 1
+      - name: Run mypy
+        run: |
+          . venv/bin/activate
+          pre-commit run --hook-stage manual mypy --all-files --show-diff-on-failure
+
   run-pylint:
     name: Run pylint
     runs-on: ubuntu-20.04
@@ -248,9 +287,7 @@ jobs:
       - name: Run pylint
         run: |
           . venv/bin/activate
-          python --version
-          pylint --version
-          pylint viseron
+          pre-commit run --hook-stage manual pylint --all-files --show-diff-on-failure
 
   run-flake8:
     name: Run flake8
