run pytest and upload coverage

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,10 +16,10 @@ env:
   BUILDKIT_PROGRESS: plain
 
 jobs:
-  prepare-pre-commit:
-    name: Prepare pre-commit
+  prepare-python-venv:
+    name: Prepare Python venv
     runs-on: ubuntu-latest
-    steps:
+    steps: 
       # Create Python virtual env used for linters
       - name: Check out code from GitHub
         uses: actions/checkout@v2.3.4
@@ -37,18 +37,42 @@ jobs:
         with:
           path: venv
           key: >-
-            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
+            ${{ runner.os }}-prepare-python-venv-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
           restore-keys: |
-            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
-            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-
-            ${{ runner.os }}-prepare-pre-commit-
+            ${{ runner.os }}-prepare-python-venv-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
+            ${{ runner.os }}-prepare-python-venv-${{ env.cache-name }}-
+            ${{ runner.os }}-prepare-python-venv-
             ${{ runner.os }}-
       - name: Create Python virtual environment
         if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
           python -m venv venv
           . venv/bin/activate
-          pip install -r requirements_test.txt
+          pip install -r requirements_ci.txt
+
+  prepare-pre-commit:
+    name: Prepare pre-commit
+    runs-on: ubuntu-latest
+    needs: prepare-python-venv
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v2.2.2
+        id: python
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2.1.6
+        with:
+          path: venv
+          key: ${{ runner.os }}-prepare-python-venv-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
       # Install pre-commit hooks into the cached virtual environment
       - name: Cache pre-commit Python virtual env
         id: cache-pre-commit
@@ -58,13 +82,13 @@ jobs:
         with:
           path: ${{ env.PRE_COMMIT_CACHE }}
           key: >-
-            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
+            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
           restore-keys: |
             ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
             ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-
             ${{ runner.os }}-prepare-pre-commit-
             ${{ runner.os }}-
-      - name: Install pre-commit and its dependencies
+      - name: Install pre-commit hooks
         if: steps.cache-pre-commit.outputs.cache-hit != 'true'
         run: |
           . venv/bin/activate
@@ -87,7 +111,7 @@ jobs:
         uses: actions/cache@v2.1.6
         with:
           path: venv
-          key: ${{ runner.os }}-prepare-pre-commit-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
+          key: ${{ runner.os }}-prepare-python-venv-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
       - name: Fail job if Python cache restore failed
         if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
@@ -98,7 +122,7 @@ jobs:
         uses: actions/cache@v2.1.6
         with:
           path: ${{ env.PRE_COMMIT_CACHE }}
-          key: ${{ runner.os }}-prepare-pre-commit-cache-pre-commit-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
+          key: ${{ runner.os }}-prepare-pre-commit-cache-pre-commit-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
       - name: Fail job if pre-commit cache restore failed
         if: steps.cache-pre-commit.outputs.cache-hit != 'true'
         run: |
@@ -113,9 +137,26 @@ jobs:
   run-pytest:
     name: Run Pytest
     runs-on: ubuntu-latest
+    needs: prepare-python-venv
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2.3.4
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v2.2.2
+        id: python
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2.1.6
+        with:
+          path: venv
+          key: ${{ runner.os }}-prepare-python-venv-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
       - name: Pull current Docker dev tag 
         run: |
           docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env pull amd64-viseron
@@ -131,6 +172,12 @@ jobs:
       - name: Build Pytest Docker image
         run: |
           docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env build --build-arg BUILDKIT_INLINE_CACHE=1 amd64-viseron-tests
-      - name: Load Docker image
+      - name: Run Pytest
         run: |
-          docker image ls -a
+          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env up amd64-viseron-tests
+      - name: Copy .coverage to host
+        run: |
+          docker cp amd64-viseron-tests:/src/coverage.xml coverage.xml
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1.5.2
+
