feat(ci): add ruff to CI without enforcing

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -388,6 +388,42 @@ jobs:
           command: |
             pre-commit run --hook-stage manual pyupgrade --all-files --show-diff-on-failure
 
+  # Run ruff, but dont fail yet since we are in the process of migrating
+  run-ruff:
+    name: Run ruff
+    runs-on: ubuntu-22.04
+    needs: [prepare-python-venv, prepare-pre-commit]
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.5.2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v4.3.0
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v4
+        with:
+          path: venv
+          key: ${{ needs.prepare-python-venv.outputs.python-venv-cache-key }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run ruff check
+        uses: ./.github/templates/run_in_venv
+        with:
+          command: |
+            ruff --version
+            ruff check viseron || true
+      - name: Run ruff format check
+        uses: ./.github/templates/run_in_venv
+        with:
+          command: |
+            ruff format --check viseron || true
+
   run-pytest:
     name: Run pytest
     runs-on: ubuntu-22.04
